In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
"D:\visual projects\Sharnouby_data"

In [6]:

data_dir = r"D:\visual projects\Sharnouby_data" 

dfs = {}

for file in os.listdir(data_dir):
    if file.endswith('.csv'):
        file_path = os.path.join(data_dir, file)
        # استخراج اسم الجدول بدون .csv لاستخدامه كمعرف
        table_name = file.replace('.csv', '')
        try:
            dfs[table_name] = pd.read_csv(file_path)
            print(f"Loaded successfully: {file} | Shape: {dfs[table_name].shape}")
        except Exception as e:
            print(f"Error loading {file}: {e}")

print(f"\nTotal tables loaded: {len(dfs)}")

Loaded successfully: Business_Units.csv | Shape: (5, 5)
Loaded successfully: Case_Briefs.csv | Shape: (10, 4)
Loaded successfully: Customers.csv | Shape: (30000, 9)
Loaded successfully: Customer_Service.csv | Shape: (6500, 9)
Loaded successfully: Data_Dictionary.csv | Shape: (19, 4)
Loaded successfully: Group_Operations.csv | Shape: (180, 7)
Loaded successfully: Inventory_History.csv | Shape: (6372, 19)
Loaded successfully: Locations.csv | Shape: (5, 9)
Loaded successfully: Machine_Downtime.csv | Shape: (2800, 8)
Loaded successfully: Marketing.csv | Shape: (420, 15)
Loaded successfully: Materials.csv | Shape: (12, 6)
Loaded successfully: Printing_Batches.csv | Shape: (1900, 15)
Loaded successfully: Production_Orders.csv | Shape: (2500, 16)
Loaded successfully: Product_BOM.csv | Shape: (337, 7)
Loaded successfully: Product_Master.csv | Shape: (59, 12)
Loaded successfully: Purchase_Orders.csv | Shape: (3600, 13)
Loaded successfully: Quality.csv | Shape: (9000, 12)
Loaded successfully: Sales_Transactions.csv | Shape: (180000, 30)
Loaded successfully: Suppliers.csv | Shape: (12, 7)
Loaded successfully: Web_Traffic_Daily.csv | Shape: (1096, 11)

Total tables loaded: 20

In [ ]:

business_units_df = dfs['Business_Units']
case_briefs_df = dfs['Case_Briefs']
customer_service_df = dfs['Customer_Service']
customers_df = dfs['Customers']
data_dictionary_df = dfs['Data_Dictionary']
group_operations_df = dfs['Group_Operations']
inventory_history_df = dfs['Inventory_History']
locations_df = dfs['Locations']
machine_downtime_df = dfs['Machine_Downtime']
marketing_df = dfs['Marketing']
materials_df = dfs['Materials']
printing_batches_df = dfs['Printing_Batches']
product_bom_df = dfs['Product_BOM']
product_master_df = dfs['Product_Master']
production_orders_df = dfs['Production_Orders']
purchase_orders_df = dfs['Purchase_Orders']
quality_df = dfs['Quality']
sales_transactions_df = dfs['Sales_Transactions']
suppliers_df = dfs['Suppliers']
web_traffic_daily_df = dfs['Web_Traffic_Daily']

In [105]:
dfs['Product_Master']

,Product_ID,SKU,Product_Name,Brand,Product_Family,Gender,Audience,Catalog_Season,Sizes,Public_Retail_Price_EGP,Public_Catalog_Source,Verification_Class
0,P001,26115-8,Summer children's girls-Happy,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
1,P002,26115-6,Summer children's girls-turtle,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
2,P003,26115-5,Summer children's girls-Hello kitty Rose & tur...,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
3,P004,26115-7,Summer children's girls-Hello kitty black&white,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
4,P005,26115-2,Summer children's boys-Black and orange,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
5,P006,26115-1,Summer children's boys-Sonic,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
6,P007,26115-3,Summer children's boys-Black and turquoise,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
7,P008,26115-4,Summer children's boys-SpongeBob,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",348,https://leo.moda/shop/,Public catalog product / public retail price
8,P009,LEO-WC-P-5404,Boys' summer t-shirt-Aubergine,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
9,P010,LEO-WC-P-5403,Boys' summer t-shirt-olive,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
10,P011,LEO-WC-P-5402,Boys' summer t-shirt-Navy blue,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
11,P012,LEO-WC-P-5401,Boys' summer t-shirt-light beige,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
12,P013,CAT-013,Boys' summer t-shirt-Beige,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
13,P014,CAT-014,Boys' summer t-shirt-Black,Leo Moda,T-Shirts,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",330,https://leo.moda/shop/,Public catalog product / public retail price
14,P015,CAT-015,Girls' summer pajamas-Stay cool,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
15,P016,CAT-016,Girls' summer pajamas-Watercolor Floral,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
16,P017,CAT-017,Girls' summer pajamas-flower,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
17,P018,CAT-018,Boys' summer pajamas-Wear your attitude,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
18,P019,CAT-019,Boys' summer pajamas- Seeds OF,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
19,P020,CAT-020,Boys' summer pajamas-Rock Band,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
20,P021,CAT-021,Girls' summer pajamas-Minnie Mouse,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
21,P022,CAT-022,Girls' summer pajamas-Stitch,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
22,P023,CAT-023,Girls' summer pajamas-Dumbo,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
23,P024,CAT-024,Boys' summer pajamas-Mickey,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
24,P025,CAT-025,Boys' summer pajamas-Snoopy,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
25,P026,CAT-026,Boys' summer pajamas-Bluey,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",299,https://leo.moda/shop/,Public catalog product / public retail price
26,P027,CAT-027,Girls' pajamas - I'm Just a girl,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",295,https://leo.moda/shop/,Public catalog product / public retail price
27,P028,CAT-028,Girls' summer pajamas,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",295,https://leo.moda/shop/,Public catalog product / public retail price
28,P029,CAT-029,Girls' pajamas-Daylife+kuromi,Leo Moda,Pajamas/Homewear,Girls,Kids,Summer 2026,"4, 6, 8, 10, 12",295,https://leo.moda/shop/,Public catalog product / public retail price
29,P030,CAT-030,Boys' pajamas -Mickey Mouse,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",295,https://leo.moda/shop/,Public catalog product / public retail price
30,P031,CAT-031,Boys' pajamas -Don't Even!,Leo Moda,Pajamas/Homewear,Boys,Kids,Summer 2026,"4, 6, 8, 10, 12",295,https://leo.moda/shop/,Public catalog product / public retail price
31,P032,CAT-032,Boys' sweatshirt-blue,Leo Moda,Sweatshirts,Boys,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
32,P033,CAT-033,Boys' sweatshirt-LEO,Leo Moda,Sweatshirts,Boys,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
33,P034,CAT-034,Boys' sweatshirt-black and white,Leo Moda,Sweatshirts,Boys,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
34,P035,CAT-035,Girls' sweatshirt-Fuchsia,Leo Moda,Sweatshirts,Girls,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
35,P036,CAT-036,Girls' sweatshirt-Tinker Bell,Leo Moda,Sweatshirts,Girls,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
36,P037,CAT-037,Girls' sweatshirt-Flower,Leo Moda,Sweatshirts,Girls,Kids,Autumn/Winter,"4, 6, 8, 10, 12",549,https://leo.moda/shop/,Public catalog product / public retail price
37,P038,CAT-038,Boys' Autumn Pajamas-Mickey Mouse,Leo Moda,Pajamas/Homewear,Boys,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
38,P039,CAT-039,Boys' Autumn Pajamas-Spider Man,Leo Moda,Pajamas/Homewear,Boys,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
39,P040,CAT-040,Boys' Autumn Pajamas-Loony Tunes,Leo Moda,Pajamas/Homewear,Boys,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
40,P041,CAT-041,Boys' Autumn Pajamas-Jurassic Park,Leo Moda,Pajamas/Homewear,Boys,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
41,P042,CAT-042,Girls' autumn pajamas-Cheeky Charmins,Leo Moda,Pajamas/Homewear,Girls,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
42,P043,CAT-043,Girls' autumn pajamas-Snow White,Leo Moda,Pajamas/Homewear,Girls,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
43,P044,CAT-044,Girls' autumn pajamas-Ice Cream,Leo Moda,Pajamas/Homewear,Girls,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
44,P045,CAT-045,Girls' autumn pajamas-Stitch,Leo Moda,Pajamas/Homewear,Girls,Kids,Autumn 2025,"4, 6, 8, 10, 12",289,https://leo.moda/shop/,Public catalog product / public retail price
45,P046,CAT-046,Mustard - طقم تيشيرت وشورت اطفال صيفي,Leo Moda,Kids Sets,Unisex,Kids,Summer,"4, 6, 8, 10, 12",400,https://leo.moda/shop/,Public catalog product / public retail price
46,P047,CAT-047,Mauve - طقم تيشيرت وشورت اطفال صيفي,Leo Moda,Kids Sets,Unisex,Kids,Summer,"4, 6, 8, 10, 12",400,https://leo.moda/shop/,Public catalog product / public retail price
47,P048,CAT-048,Semon - طقم تيشيرت وشورت اطفال صيفي,Leo Moda,Kids Sets,Unisex,Kids,Summer,"4, 6, 8, 10, 12",400,https://leo.moda/shop/,Public catalog product / public retail price
48,P049,CAT-049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,Leo Moda,Kids Sets,Girls,Kids,Summer,"4, 6, 8, 10, 12",400,https://leo.moda/shop/,Public catalog product / public retail price
49,P050,CAT-050,Yellow - طقم تيشيرت وشورت اطفال صيفي,Leo Moda,Kids Sets,Unisex,Kids,Summer,"4, 6, 8, 10, 12",400,https://leo.moda/shop/,Public catalog product / public retail price
50,P051,CAT-051,Ice cream - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
51,P052,CAT-052,Teddy bear - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
52,P053,CAT-053,PINK panther - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
53,P054,CAT-054,Gazelle - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
54,P055,CAT-055,Scooby-Doo - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
55,P056,CAT-056,BATGIRL - بيجامة حريمي صيفي2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
56,P057,CAT-057,Save the planet بيجامة حريمي صيفي - 2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
57,P058,CAT-058,OHANA - بيجامة حريمي صيفي 2024,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price
58,P059,CAT-059,Positive vibes - 2024بيجامة حريمي صيفي,Leo Moda,Pajamas/Homewear,Women,Women,Summer 2024,"M, L, XL, 2XL",388,https://leo.moda/shop/,Public catalog product / public retail price

In [104]:
dfs['Marketing']

,Campaign_ID,Campaign_Name,Product_ID,Product_Name,Platform,Start_Date,End_Date,Spend_EGP,Impressions,Clicks,Landing_Page_Sessions,Orders_Attributed,Attributed_Revenue_EGP,Discount_Pct,Data_Class
0,CMP0001,Meta | Boys' summer pajamas-Wear your a | May24,P018,Boys' summer pajamas-Wear your attitude,Meta,2024-05-24,2024-06-08,24313,549466,6835,6835,103,41337.81,0.15,Modeled campaign performance - not actual medi...
1,CMP0002,TikTok | Girls' pajamas-Daylife+kuromi | Dec24,P029,Girls' pajamas-Daylife+kuromi,TikTok,2024-12-24,2024-12-29,25303,626807,13393,13393,193,95701.65,0.10,Modeled campaign performance - not actual medi...
2,CMP0003,Google | Boys' Autumn Pajamas-Loony Tunes | Oct25,P040,Boys' Autumn Pajamas-Loony Tunes,Google,2025-10-22,2025-11-13,47808,542947,17336,17336,881,353823.52,0.00,Modeled campaign performance - not actual medi...
3,CMP0004,Meta | Girls' summer pajamas-Stay cool | Mar24,P015,Girls' summer pajamas-Stay cool,Meta,2024-03-26,2024-04-09,55766,795931,15690,15690,252,98952.32,0.20,Modeled campaign performance - not actual medi...
4,CMP0005,Meta | Fuchsia - طقم تيشيرت وشورت اطفال | Mar25,P049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,Meta,2025-03-07,2025-03-19,39530,597865,13586,13586,197,107103.87,0.20,Modeled campaign performance - not actual medi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,CMP0416,Influencer | Boys' sweatshirt-blue | Oct23,P032,Boys' sweatshirt-blue,Influencer,2023-10-10,2023-10-23,35035,268257,2594,2594,32,27826.35,0.20,Modeled campaign performance - not actual medi...
416,CMP0417,Influencer | Summer children's girls-Happy | A...,P001,Summer children's girls-Happy,Influencer,2026-04-27,2026-05-25,50895,368149,3075,3075,59,31139.09,0.00,Modeled campaign performance - not actual medi...
417,CMP0418,Google | Girls' autumn pajamas-Snow White | Nov25,P043,Girls' autumn pajamas-Snow White,Google,2025-11-11,2025-12-09,39375,537466,24875,24875,1239,525221.28,0.00,Modeled campaign performance - not actual medi...
418,CMP0419,Meta | Boys' Autumn Pajamas-Mickey Mous | Nov23,P038,Boys' Autumn Pajamas-Mickey Mouse,Meta,2023-11-23,2023-12-14,64285,1282984,15862,15862,501,233953.33,0.25,Modeled campaign performance - not actual medi...
419,CMP0420,TikTok | Girls' pajamas-Daylife+kuromi | Jun25,P029,Girls' pajamas-Daylife+kuromi,TikTok,2025-06-12,2025-07-09,37570,729103,17444,17444,208,65826.45,0.20,Modeled campaign performance - not actual medi...

In [103]:
dfs['Suppliers']

,Supplier_ID,Supplier_Name,Primary_Category,Governorate,Payment_Terms_Days,Contracted,Data_Class
0,SUP01,Approved Supplier 01 (anonymized),Packaging,Beheira,45,No,Modeled training record - supplier identity an...
1,SUP02,Approved Supplier 02 (anonymized),Trims,Alexandria,15,Yes,Modeled training record - supplier identity an...
2,SUP03,Approved Supplier 03 (anonymized),Fabric,Gharbia,45,No,Modeled training record - supplier identity an...
3,SUP04,Approved Supplier 04 (anonymized),Printing Consumables,Beheira,60,Yes,Modeled training record - supplier identity an...
4,SUP05,Approved Supplier 05 (anonymized),Fabric,Cairo,45,No,Modeled training record - supplier identity an...
5,SUP06,Approved Supplier 06 (anonymized),Packaging,Gharbia,60,Yes,Modeled training record - supplier identity an...
6,SUP07,Approved Supplier 07 (anonymized),Packaging,Cairo,15,Yes,Modeled training record - supplier identity an...
7,SUP08,Approved Supplier 08 (anonymized),Trims,Gharbia,45,No,Modeled training record - supplier identity an...
8,SUP09,Approved Supplier 09 (anonymized),Trims,Alexandria,30,No,Modeled training record - supplier identity an...
9,SUP10,Approved Supplier 10 (anonymized),Trims,Dakahlia,45,Yes,Modeled training record - supplier identity an...
10,SUP11,Approved Supplier 11 (anonymized),Trims,Gharbia,15,Yes,Modeled training record - supplier identity an...
11,SUP12,Approved Supplier 12 (anonymized),Fabric,Dakahlia,15,Yes,Modeled training record - supplier identity an...

In [102]:
dfs['Printing_Batches']

,Print_Batch_ID,Product_ID,Product_Name,Print_Date,Print_Type,Machine_ID,Planned_Qty,Printed_Qty,Good_Qty,Rejected_Qty,Reprint_Qty,Defect_Type,Ink_or_Consumable_Cost_EGP,Rework_Cost_EGP,Data_Class
0,PR00001,P015,Girls' summer pajamas-Stay cool,2023-10-29,Digital,PR-M02,3240,3119,3055,64,31,No Defect,12570.15,178.57,Modeled print operation
1,PR00002,P051,Ice cream - بيجامة حريمي صيفي2024,2025-05-13,Water-Based,PR-M02,949,926,882,44,31,Curing,6152.74,244.02,Modeled print operation
2,PR00003,P015,Girls' summer pajamas-Stay cool,2025-07-20,Heat Transfer,PR-M05,5242,5185,5007,178,81,Curing,24019.22,375.21,Modeled print operation
3,PR00004,P037,Girls' sweatshirt-Flower,2023-12-14,Heat Transfer,PR-M04,4682,4582,4495,87,73,No Defect,24506.50,552.16,Modeled print operation
4,PR00005,P043,Girls' autumn pajamas-Snow White,2023-12-11,Digital,PR-M03,5480,5521,5444,77,68,Registration,15642.27,425.81,Modeled print operation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,PR01896,P043,Girls' autumn pajamas-Snow White,2023-12-12,Screen,PR-M05,625,621,597,24,12,Print Cracking,2211.67,78.93,Modeled print operation
1896,PR01897,P054,Gazelle - بيجامة حريمي صيفي2024,2025-05-17,Water-Based,PR-M04,2001,2008,1919,89,75,Color Misalignment,6480.50,457.76,Modeled print operation
1897,PR01898,P005,Summer children's boys-Black and orange,2025-06-30,Digital,PR-M01,780,784,759,25,19,Curing,4414.68,137.65,Modeled print operation
1898,PR01899,P058,OHANA - بيجامة حريمي صيفي 2024,2025-01-05,Water-Based,PR-M02,2487,2433,2395,38,18,Registration,11254.51,118.70,Modeled print operation
1899,PR01900,P052,Teddy bear - بيجامة حريمي صيفي2024,2024-06-25,Digital,PR-M03,5268,5197,5115,82,50,Curing,30054.84,423.70,Modeled print operation

In [100]:
locations_df

,Location_ID,Location_Name,Location_Type,Channel,Governorate,City,Public_Address,Source_URL,Verification_Class
0,LOC001,LEO MODA - Sidi Bishr Store,Retail Store,Retail,Alexandria,Sidi Bishr,"72C2+GXJ, Sidi Bishr Bahri, Montaza 2, Alexand...",https://leo.moda/our-stores/,Public store / address cross-checked from publ...
1,LOC002,LEO MODA Online Store,Digital Store,Online,Egypt,Nationwide,Online - delivery across Egypt,https://leo.moda/,Public channel
2,LOC003,El-Sharnouby Wholesale Desk,B2B / Wholesale,Wholesale,Alexandria,Zizinia,"5 Amin Yehia Street, Zizinia, Alexandria, Egypt",https://www.el-sharnouby.com/,Public HQ / wholesale inquiry channel
3,LOC004,El-Sharnouby Head Office,Head Office,Corporate,Alexandria,Zizinia,"5 Amin Yehia Street, Zizinia, Alexandria, Egypt",https://www.el-sharnouby.com/,Public HQ
4,LOC005,LEO Production Hub,Factory / Production,Operations,Alexandria,Alexandria,"Alexandria, Egypt",https://www.el-sharnouby.com/services,Public business unit; exact facility address n...

In [12]:
business_units_df

,Business_Unit,Function,Public_Capacity,Source_URL,Verification_Class
0,LEO DESIGN,"Fashion design, pattern making, 3D visualization",Not publicly stated,https://www.el-sharnouby.com/,Public company fact
1,LEO TEX,Woven fabric manufacturing,Integrated textile manufacturing; exact capaci...,https://www.el-sharnouby.com/services,Public company fact
2,LEO PRODUCTION HUB,Garment manufacturing,"Up to 5,000 pieces/day",https://www.el-sharnouby.com/services,Public company fact
3,LEO PRINT,Textile and garment printing,"Up to 20,000 garments/day and 6,000 fabric met...",https://www.el-sharnouby.com/services,Public company fact
4,LEO MODA,"Retail, online and wholesale apparel brand",Delivery across Egypt; retail + wholesale chan...,https://leo.moda/,Public company fact

In [13]:

case_briefs_df

,Card_No,Title,Business_Problem,Expected_Deliverable
0,1,Executive Sales & Profitability,"Revenue is growing, but management is unsure w...","Build an executive view of revenue, units, gro..."
1,2,Customer 360 & Retention,"The business has a growing customer base, but ...","Create customer segments using RFM/cohorts, re..."
2,3,Branch & Channel Performance,"Retail, online and wholesale operate different...","Compare channel growth, margin, returns, baske..."
3,4,Inventory & Demand Planning,Some SKUs tie up cash while other fast movers ...,"Perform ABC/XYZ analysis, stock turns, days of..."
4,5,Marketing Effectiveness,"Spend is distributed across platforms, but man...","Measure ROAS, CAC, CTR, conversion, attributed..."
5,6,Factory Production & Bottlenecks,Production orders show uneven efficiency and d...,"Analyze throughput, plan vs actual, reject rat..."
6,7,"Quality, Returns & Cost of Poor Quality",Customer returns and QC defects are not always...,"Build defect Pareto, quality loss, product/sta..."
7,8,Printing Performance & Downtime,Printing yield and rework vary by machine and ...,"Analyze machine yield, defect rate, reprint co..."
8,9,Supply Chain & Materials,Material availability and supplier reliability...,"Measure supplier lead time, on-time delivery, ..."
9,10,Integrated Management Story + Forecast,Leadership needs one connected story from mark...,Deliver a management dashboard/story that link...

In [26]:
sales_transactions_df.head(5)

,Row_ID,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,...,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class
0,0,INV0000001,2024-05-11,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,...,247.57,82.23,0.2493,Wallet,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
1,1,INV0000002,2025-07-31,2025-07,LOC001,LEO MODA - Sidi Bishr Store,Retail,C22543,Retail,Alexandria,...,163.31,67.89,0.2936,Card,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
2,2,INV0000003,2026-05-23,2026-05,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C13351,Wholesale,Alexandria,...,4301.71,512.69,0.1065,Cash,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
3,3,INV0000004,2024-06-05,2024-06,LOC003,El-Sharnouby Wholesale Desk,Wholesale,C21377,Wholesale,Dakahlia,...,10451.13,907.59,0.0799,Bank Transfer,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...
4,4,INV0000005,2025-12-28,2025-12,LOC001,LEO MODA - Sidi Bishr Store,Retail,C21499,Retail,Alexandria,...,186.16,53.04,0.2217,Cash,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...

In [16]:
sales_transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Row_ID                  180000 non-null  int64
 1   Invoice_ID              180000 non-null  object
 2   Order_Date              180000 non-null  object
 3   Month_Key               180000 non-null  object
 4   Location_ID             180000 non-null  object
 5   Location_Name           180000 non-null  object
 6   Channel                 180000 non-null  object
 7   Customer_ID             180000 non-null  object
 8   Customer_Type           180000 non-null  object
 9   Customer_Governorate    180000 non-null  object
 10  Product_ID              180000 non-null  object
 11  SKU                     180000 non-null  object
 12  Product_Name            180000 non-null  object
 13  Product_Family          180000 non-null  object
 14  Size                    180000 non-null  object
 15  Quantity                180000 non-null  int64
 16  List_Price_EGP          180000 non-null  int64
 17  Discount_Pct            180000 non-null  float64
 18  Gross_Sales_EGP         180000 non-null  int64
 19  Net_Sales_EGP           180000 non-null  float64
 20  Estimated_COGS_EGP      180000 non-null  float64
 21  Gross_Profit_EGP        180000 non-null  float64
 22  Gross_Margin_Pct        180000 non-null  float64
 23  Payment_Method          180000 non-null  object
 24  Returned                180000 non-null  object
 25  Return_Date             8543 non-null    object
 26  Return_Reason           180000 non-null  object
 27  Refund_Value_EGP        180000 non-null  float64
 28  Quality_Related_Return  180000 non-null  object
 29  Data_Class              180000 non-null  object
dtypes: float64(6), int64(4), object(20)
memory usage: 41.2+ MB

In [19]:

found_nulls = False

for table_name, df in dfs.items():
    null_counts = df.isnull().sum()
    null_counts = null_counts[null_counts > 0] # الأعمدة التي بها نالس فقط
    
    if not null_counts.empty:
        found_nulls = True
        print(f" {table_name}")
        for col, count in null_counts.items():
            pct = (count / len(df)) * 100
            print(f"{col}': {count} قيمة مفقودة ({pct:.2f}%)")

if not found_nulls:
    print("\n مبروك! لا توجد أي قيم مفقودة في أي جدول بالكامل.")

 Printing_Batches
Defect_Type': 381 قيمة مفقودة (20.05%)
 Production_Orders
Primary_Bottleneck': 2093 قيمة مفقودة (83.72%)
 Quality
Defect_Type': 1972 قيمة مفقودة (21.91%)
 Sales_Transactions
Return_Date': 171457 قيمة مفقودة (95.25%)

In [22]:
printing_batches_df

,Print_Batch_ID,Product_ID,Product_Name,Print_Date,Print_Type,Machine_ID,Planned_Qty,Printed_Qty,Good_Qty,Rejected_Qty,Reprint_Qty,Defect_Type,Ink_or_Consumable_Cost_EGP,Rework_Cost_EGP,Data_Class
0,PR00001,P015,Girls' summer pajamas-Stay cool,2023-10-29,Digital,PR-M02,3240,3119,3055,64,31,NaN,12570.15,178.57,Modeled print operation
1,PR00002,P051,Ice cream - بيجامة حريمي صيفي2024,2025-05-13,Water-Based,PR-M02,949,926,882,44,31,Curing,6152.74,244.02,Modeled print operation
2,PR00003,P015,Girls' summer pajamas-Stay cool,2025-07-20,Heat Transfer,PR-M05,5242,5185,5007,178,81,Curing,24019.22,375.21,Modeled print operation
3,PR00004,P037,Girls' sweatshirt-Flower,2023-12-14,Heat Transfer,PR-M04,4682,4582,4495,87,73,NaN,24506.50,552.16,Modeled print operation
4,PR00005,P043,Girls' autumn pajamas-Snow White,2023-12-11,Digital,PR-M03,5480,5521,5444,77,68,Registration,15642.27,425.81,Modeled print operation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,PR01896,P043,Girls' autumn pajamas-Snow White,2023-12-12,Screen,PR-M05,625,621,597,24,12,Print Cracking,2211.67,78.93,Modeled print operation
1896,PR01897,P054,Gazelle - بيجامة حريمي صيفي2024,2025-05-17,Water-Based,PR-M04,2001,2008,1919,89,75,Color Misalignment,6480.50,457.76,Modeled print operation
1897,PR01898,P005,Summer children's boys-Black and orange,2025-06-30,Digital,PR-M01,780,784,759,25,19,Curing,4414.68,137.65,Modeled print operation
1898,PR01899,P058,OHANA - بيجامة حريمي صيفي 2024,2025-01-05,Water-Based,PR-M02,2487,2433,2395,38,18,Registration,11254.51,118.70,Modeled print operation
1899,PR01900,P052,Teddy bear - بيجامة حريمي صيفي2024,2024-06-25,Digital,PR-M03,5268,5197,5115,82,50,Curing,30054.84,423.70,Modeled print operation

In [23]:

printing_batches_df['Defect_Type'] = printing_batches_df['Defect_Type'].fillna('No Defect')


quality_df['Defect_Type'] = quality_df['Defect_Type'].fillna('No Defect')

production_orders_df['Primary_Bottleneck'] = production_orders_df['Primary_Bottleneck'].fillna('No Bottleneck')


print("Printing_Batches Nulls:", printing_batches_df['Defect_Type'].isnull().sum())
print("Quality Nulls:", quality_df['Defect_Type'].isnull().sum())
print("Production_Orders Nulls:", production_orders_df['Primary_Bottleneck'].isnull().sum())

Printing_Batches Nulls: 0
Quality Nulls: 0
Production_Orders Nulls: 0

In [91]:
sales_transactions_df.head(1)

,Row_ID,Invoice_ID,Order_Date,Month_Key,Location_ID,Location_Name,Channel,Customer_ID,Customer_Type,Customer_Governorate,...,Estimated_COGS_EGP,Gross_Profit_EGP,Gross_Margin_Pct,Payment_Method,Returned,Return_Date,Return_Reason,Refund_Value_EGP,Quality_Related_Return,Data_Class
0,0,INV0000001,2024-05-11,2024-05,LOC002,LEO MODA Online Store,Online,C18976,Retail,Cairo,...,247.57,82.23,0.2493,Wallet,No,NaN,No return,0.0,No,Modeled training transaction anchored to publi...

In [88]:
sales_transactions_df.columns

Index(['Row_ID', 'Invoice_ID', 'Order_Date', 'Month_Key', 'Location_ID',
       'Location_Name', 'Channel', 'Customer_ID', 'Customer_Type',
       'Customer_Governorate', 'Product_ID', 'SKU', 'Product_Name',
       'Product_Family', 'Size', 'Quantity', 'List_Price_EGP', 'Discount_Pct',
       'Gross_Sales_EGP', 'Net_Sales_EGP', 'Estimated_COGS_EGP',
       'Gross_Profit_EGP', 'Gross_Margin_Pct', 'Payment_Method', 'Returned',
       'Return_Date', 'Return_Reason', 'Refund_Value_EGP',
       'Quality_Related_Return', 'Data_Class'],
      dtype='object')

In [98]:
sales_transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Row_ID                  180000 non-null  int64
 1   Invoice_ID              180000 non-null  object
 2   Order_Date              180000 non-null  object
 3   Month_Key               180000 non-null  object
 4   Location_ID             180000 non-null  object
 5   Location_Name           180000 non-null  object
 6   Channel                 180000 non-null  object
 7   Customer_ID             180000 non-null  object
 8   Customer_Type           180000 non-null  object
 9   Customer_Governorate    180000 non-null  object
 10  Product_ID              180000 non-null  object
 11  SKU                     180000 non-null  object
 12  Product_Name            180000 non-null  object
 13  Product_Family          180000 non-null  object
 14  Size                    180000 non-null  object
 15  Quantity                180000 non-null  int64
 16  List_Price_EGP          180000 non-null  int64
 17  Discount_Pct            180000 non-null  float64
 18  Gross_Sales_EGP         180000 non-null  int64
 19  Net_Sales_EGP           180000 non-null  float64
 20  Estimated_COGS_EGP      180000 non-null  float64
 21  Gross_Profit_EGP        180000 non-null  float64
 22  Gross_Margin_Pct        180000 non-null  float64
 23  Payment_Method          180000 non-null  object
 24  Returned                180000 non-null  object
 25  Return_Date             8543 non-null    object
 26  Return_Reason           180000 non-null  object
 27  Refund_Value_EGP        180000 non-null  float64
 28  Quality_Related_Return  180000 non-null  object
 29  Data_Class              180000 non-null  object
dtypes: float64(6), int64(4), object(20)
memory usage: 41.2+ MB

In [24]:

total_net_sales = sales_transactions_df['Net_Sales_EGP'].sum()
total_cogs = sales_transactions_df['Estimated_COGS_EGP'].sum()
total_gross_profit = sales_transactions_df['Gross_Profit_EGP'].sum()
overall_margin = (total_gross_profit / total_net_sales) * 100

print("--- Executive Financial KPIs ---")
print(f"Total Net Sales: {total_net_sales:,.2f} EGP")
print(f"Total COGS: {total_cogs:,.2f} EGP")
print(f"Total Gross Profit: {total_gross_profit:,.2f} EGP")
print(f"Overall Gross Margin: {overall_margin:.2f}%")

# 2. Channel Performance Analysis
channel_performance = sales_transactions_df.groupby('Channel').agg(
    Net_Sales=('Net_Sales_EGP', 'sum'),
    Gross_Profit=('Gross_Profit_EGP', 'sum'),
    Transactions_Count=('Invoice_ID', 'count')
).reset_index()

channel_performance['Margin_Pct'] = (channel_performance['Gross_Profit'] / channel_performance['Net_Sales']) * 100

print("\n--- Performance by Sales Channel ---")
display(channel_performance)

--- Executive Financial KPIs ---
Total Net Sales: 421,338,377.53 EGP
Total COGS: 356,450,087.63 EGP
Total Gross Profit: 64,888,289.90 EGP
Overall Gross Margin: 15.40%

--- Performance by Sales Channel ---

     Channel     Net_Sales  Gross_Profit  Transactions_Count  Margin_Pct
0     Online  3.262957e+07   11384070.74               71559   34.888812
1     Retail  2.934769e+07   10869176.78               61769   37.035888
2  Wholesale  3.593611e+08   42635042.38               46672   11.864122

In [27]:
monthly_performance = sales_transactions_df.groupby('Month_Key').agg(
    Net_Sales=('Net_Sales_EGP', 'sum'),
    Gross_Profit=('Gross_Profit_EGP', 'sum'),
    Quantity=('Quantity', 'sum')
).reset_index().sort_values('Month_Key')

print("--- Monthly Sales & Profitability Trend ---")
display(monthly_performance)

--- Monthly Sales & Profitability Trend ---

   Month_Key    Net_Sales  Gross_Profit  Quantity
0    2023-10   9663345.29    1558433.72     36484
1    2023-11  10771256.46    1712293.37     40007
2    2023-12  12277328.47    1924678.09     45928
3    2024-01   9172864.77    1461991.42     34495
4    2024-02   8800097.31    1383406.49     32923
5    2024-03  10277634.17    1605080.00     40500
6    2024-04  11486993.44    1685023.12     46938
7    2024-05  11421809.19    1678468.53     46803
8    2024-06  11792982.05    1740982.49     48357
9    2024-07  12719754.24    1872945.74     52210
10   2024-08  11606488.48    1704408.23     47810
11   2024-09   9533791.28    1478124.60     38090
12   2024-10  11076601.25    1767654.12     41744
13   2024-11  12006921.41    1890150.74     44971
14   2024-12  14602932.55    2316161.22     54461
15   2025-01  10405331.38    1630475.37     38937
16   2025-02   8694838.47    1369113.84     32725
17   2025-03  11099870.99    1709726.64     44273
18   2025-04  12392666.59    1817229.51     50780
19   2025-05  13128154.65    1969804.32     54290
20   2025-06  12790797.86    1951774.22     52126
21   2025-07  13607163.80    2036493.24     55348
22   2025-08  13249355.63    1992141.53     54648
23   2025-09  10453454.10    1568056.50     41569
24   2025-10  10035892.24    1620892.83     37453
25   2025-11  11339661.96    1802102.88     42307
26   2025-12  15635963.28    2503709.51     58762
27   2026-01  10616956.41    1722416.57     40138
28   2026-02   9515984.18    1553435.58     35362
29   2026-03  12162736.98    1874987.37     48201
30   2026-04  12262285.98    1912359.06     50135
31   2026-05  14158935.16    2135185.38     57685
32   2026-06  13686003.19    2027719.60     56301
33   2026-07  14523747.10    2132404.38     59539
34   2026-08  13312040.63    2085752.26     54091
35   2026-09  11055736.59    1692707.43     44198

In [28]:
top_customers = sales_transactions_df.groupby(['Customer_ID', 'Customer_Type', 'Customer_Governorate']).agg(
    Total_Spent=('Net_Sales_EGP', 'sum'),
    Total_Orders=('Invoice_ID', 'count')
).reset_index().sort_values(by='Total_Spent', ascending=False).head(5)

print("--- Top 5 Customers by Revenue ---")
display(top_customers)

--- Top 5 Customers by Revenue ---

,Customer_ID,Customer_Type,Customer_Governorate,Total_Spent,Total_Orders
11555,C13551,Wholesale,Sharqia,876177.02,106
495,C00582,Wholesale,Alexandria,873820.21,108
25097,C29367,Wholesale,Alexandria,869902.76,114
4411,C05154,Wholesale,Port Said,848697.90,106
11997,C14068,Wholesale,Kafr El Sheikh,838875.19,120

In [93]:
dfs['Customers'].columns

Index(['Customer_ID', 'Customer_Type', 'Governorate', 'Age_Band', 'Gender',
       'Join_Date', 'Acquisition_Channel', 'Consent_Status', 'Data_Class'],
      dtype='object')

In [29]:
governorate_performance = sales_transactions_df.groupby('Customer_Governorate').agg(
    Net_Sales=('Net_Sales_EGP', 'sum'),
    Gross_Profit=('Gross_Profit_EGP', 'sum')
).reset_index().sort_values(by='Net_Sales', ascending=False)

print("--- Sales & Profit by Governorate ---")
display(governorate_performance)

--- Sales & Profit by Governorate ---

   Customer_Governorate     Net_Sales  Gross_Profit
0            Alexandria  1.234941e+08   18762214.86
2                 Cairo  7.397313e+07   11442543.37
6                  Giza  4.877389e+07    7391961.33
1               Beheira  3.513801e+07    5343377.00
3              Dakahlia  2.780888e+07    4292598.17
5               Gharbia  2.297662e+07    3599075.20
11              Sharqia  2.081328e+07    3186983.77
9                 Other  2.062912e+07    3343447.67
7        Kafr El Sheikh  1.600547e+07    2514204.32
8               Monufia  1.050683e+07    1697424.85
10            Port Said  8.535238e+06    1315217.71
4              Damietta  7.583136e+06    1249570.97
12                 Suez  5.100685e+06     749670.68

In [30]:
returns_summary = sales_transactions_df.groupby('Returned').agg(
    Transaction_Count=('Invoice_ID', 'count'),
    Total_Refund_Value=('Refund_Value_EGP', 'sum')
).reset_index()

print("--- Returns Impact Summary ---")
display(returns_summary)

--- Returns Impact Summary ---

  Returned  Transaction_Count  Total_Refund_Value
0       No             171457                0.00
1      Yes               8543          9427005.55

In [33]:
# Production Orders Bottleneck Analysis (Corrected Column Names)
bottleneck_analysis = production_orders_df.groupby('Primary_Bottleneck').agg(
    Order_Count=('Production_Order_ID', 'count'),
    Total_Quantity=('Planned_Qty', 'sum')
).reset_index().sort_values(by='Order_Count', ascending=False)

print("--- Production Bottlenecks Analysis ---")
display(bottleneck_analysis)

--- Production Bottlenecks Analysis ---

  Primary_Bottleneck  Order_Count  Total_Quantity
2      No Bottleneck         2093         5717067
5             Sewing          134          404635
1          Finishing          109          278606
3            Packing           61          175510
0            Cutting           59          180027
4           Printing           44          141631

In [34]:
# Printing Performance by Print Type
printing_performance = printing_batches_df.groupby('Print_Type').agg(
    Total_Batches=('Print_Batch_ID', 'count'),
    Planned_Quantity=('Planned_Qty', 'sum'),
    Printed_Quantity=('Printed_Qty', 'sum'),
    Total_Ink_Cost=('Ink_or_Consumable_Cost_EGP', 'sum'),
    Total_Rework_Cost=('Rework_Cost_EGP', 'sum')
).reset_index()

print("--- Printing Performance by Type ---")
display(printing_performance)

--- Printing Performance by Type ---

,Print_Type,Total_Batches,Planned_Quantity,Printed_Quantity,Total_Ink_Cost,Total_Rework_Cost
0,Digital,492,1552296,1529057,6603660.94,210571.10
1,Heat Transfer,467,1467381,1446027,6600500.48,193867.57
2,Screen,468,1483169,1461024,6451167.53,197667.80
3,Water-Based,473,1448421,1424624,6420258.08,193481.18

In [37]:
# Inventory Valuation & Stock Levels by Location
inventory_summary = inventory_history_df.groupby(['Location_ID', 'Location_Name']).agg(
    Total_SKUs=('SKU', 'count'),
    Total_Closing_Stock=('Closing_Stock', 'sum'),
    Total_Stockout_Days=('Stockout_Days_In_Month', 'sum')
).reset_index().sort_values(by='Total_Closing_Stock', ascending=False)

print("--- Inventory Levels and Stockout Summary by Location ---")
display(inventory_summary)

--- Inventory Levels and Stockout Summary by Location ---

,Location_ID,Location_Name,Total_SKUs,Total_Closing_Stock,Total_Stockout_Days
2,LOC003,El-Sharnouby Wholesale Desk,2124,1091124,1153
1,LOC002,LEO MODA Online Store,2124,651235,30
0,LOC001,LEO MODA - Sidi Bishr Store,2124,569753,14

In [40]:
# Customer Segmentation Analysis by Type, Governorate, and Channel
customer_segmentation = customers_df.groupby(['Customer_Type', 'Governorate', 'Acquisition_Channel']).agg(
    Total_Customers=('Customer_ID', 'count')
).reset_index().sort_values(by='Total_Customers', ascending=False)

print("--- Customer Segmentation Summary ---")
display(customer_segmentation)

--- Customer Segmentation Summary ---

   Customer_Type Governorate Acquisition_Channel  Total_Customers
0         Retail  Alexandria   Direct / WhatsApp             1776
2         Retail  Alexandria      Organic Social             1568
5         Retail  Alexandria       Store Walk-in             1474
3         Retail  Alexandria         Paid Social             1419
12        Retail       Cairo   Direct / WhatsApp             1162
..           ...         ...                 ...              ...
88     Wholesale   Port Said     Wholesale Sales               35
82     Wholesale    Damietta     Wholesale Sales               34
73        Retail        Suez       Google Search               28
90     Wholesale        Suez     Wholesale Sales               24
76        Retail        Suez            Referral               15

[91 rows x 4 columns]

In [45]:
# Marketing Campaigns Performance Analysis by Platform
marketing_df = dfs['Marketing']

marketing_performance = marketing_df.groupby('Platform').agg(
    Total_Campaigns=('Campaign_ID', 'count'),
    Total_Spend=('Spend_EGP', 'sum'),
    Total_Revenue=('Attributed_Revenue_EGP', 'sum'),
    Total_Clicks=('Clicks', 'sum'),
    Total_Impressions=('Impressions', 'sum')
).reset_index()

# Calculate Return on Ad Spend (ROAS)
marketing_performance['ROAS'] = marketing_performance['Total_Revenue'] / marketing_performance['Total_Spend']

print("--- Marketing Performance Summary by Platform ---")
display(marketing_performance)

--- Marketing Performance Summary by Platform ---

,Platform,Total_Campaigns,Total_Spend,Total_Revenue,Total_Clicks,Total_Impressions,ROAS
0,Google,117,3890507,3.995280e+07,1833882,48653120,10.269305
1,Influencer,43,1470706,1.558888e+06,147463,11919021,1.059959
2,Meta,153,5437904,2.374271e+07,1984136,105156585,4.366151
3,TikTok,65,2238109,1.091526e+07,1160622,51056892,4.877003
4,WhatsApp / CRM,42,1546750,1.035723e+08,3600635,64328584,66.961238

In [48]:
# Customer Service Performance Analysis (Corrected Column Names)
cs_df = dfs['Customer_Service']

cs_summary = cs_df.groupby(['Issue_Type', 'Resolved']).agg(
    Total_Tickets=('Ticket_ID', 'count'),
    Avg_Resolution_Hours=('Resolution_Hours', 'mean'),
    Avg_CSAT=('CSAT_1_to_5', 'mean')
).reset_index().sort_values(by='Total_Tickets', ascending=False)

print("--- Customer Service Summary ---")
display(cs_summary)

--- Customer Service Summary ---

,Issue_Type,Resolved,Total_Tickets,Avg_Resolution_Hours,Avg_CSAT
13,Size guidance,Yes,1267,14.870955,4.076559
5,Order status,Yes,1217,14.683320,4.103533
3,General product question,Yes,1028,15.279572,4.051556
1,Exchange request,Yes,658,15.126900,4.107903
9,Product quality,Yes,631,15.772583,4.077655
15,Wholesale inquiry,Yes,579,15.515199,4.077720
11,Return request,Yes,503,14.617097,4.071571
7,Payment,Yes,297,15.199663,4.101010
12,Size guidance,No,80,63.016250,2.475000
4,Order status,No,56,62.646429,2.125000
2,General product question,No,54,65.981481,2.333333
8,Product quality,No,37,61.129730,2.054054
0,Exchange request,No,34,67.008824,2.235294
10,Return request,No,23,64.013043,2.217391
14,Wholesale inquiry,No,20,58.080000,2.800000
6,Payment,No,16,57.043750,2.500000

In [47]:
print(dfs['Customer_Service'].columns.tolist())

['Ticket_ID', 'Open_Date', 'Channel', 'Issue_Type', 'First_Response_Minutes', 'Resolution_Hours', 'Resolved', 'CSAT_1_to_5', 'Data_Class']

In [52]:
# Quality Inspections and Defect Loss Analysis (Corrected Column Names)
quality_df = dfs['Quality']

quality_summary = quality_df.groupby(['Stage', 'Defect_Type']).agg(
    Total_Inspections=('QC_ID', 'count'),
    Total_Inspected_Qty=('Inspected_Qty', 'sum'),
    Total_Rejected_Qty=('Rejected_Qty', 'sum'),
    Total_Estimated_Loss=('Estimated_Loss_EGP', 'sum')
).reset_index().sort_values(by='Total_Rejected_Qty', ascending=False)

print("--- Quality Defect and Loss Summary ---")
display(quality_summary)

--- Quality Defect and Loss Summary ---

,Stage,Defect_Type,Total_Inspections,Total_Inspected_Qty,Total_Rejected_Qty,Total_Estimated_Loss
52,Sewing,Size Variance,163,78549,2071,379152.44
49,Sewing,No Defect,335,104771,1948,352996.02
4,Cutting,No Defect,336,100724,1916,351138.33
22,Final,No Defect,336,102507,1891,349057.10
40,Printing,No Defect,311,94302,1870,330847.49
17,Fabric,Stitch Defect,156,71966,1865,330127.79
7,Cutting,Size Variance,154,67025,1858,338099.79
26,Final,Stitch Defect,154,69378,1853,332438.20
41,Printing,Packing Error,149,66904,1846,335506.25
31,Finishing,No Defect,329,95533,1819,324192.75
34,Finishing,Size Variance,159,70526,1815,334699.42
10,Fabric,Fabric Defect,156,71885,1808,334105.81
35,Finishing,Stitch Defect,154,68956,1798,340319.22
16,Fabric,Size Variance,149,69654,1787,315257.03
53,Sewing,Stitch Defect,150,68372,1780,330011.50
8,Cutting,Stitch Defect,153,69337,1779,329046.47
27,Finishing,Color Misalignment,148,69718,1775,311414.24
1,Cutting,Fabric Defect,156,69590,1774,317170.07
13,Fabric,No Defect,325,96921,1764,320666.32
50,Sewing,Packing Error,162,72471,1756,314288.50
43,Printing,Size Variance,160,70588,1723,316323.85
32,Finishing,Packing Error,153,68807,1717,317280.10
2,Cutting,Finishing Defect,141,66637,1683,312686.43
0,Cutting,Color Misalignment,145,63689,1679,301610.00
30,Finishing,Ink Smudge,155,69824,1674,295953.75
18,Final,Color Misalignment,159,65252,1663,284119.90
44,Printing,Stitch Defect,141,61042,1651,296634.80
15,Fabric,Print Cracking,159,68529,1650,313781.59
3,Cutting,Ink Smudge,150,68416,1649,305937.89
24,Final,Print Cracking,160,69513,1640,292019.53
19,Final,Fabric Defect,138,63844,1639,291836.04
39,Printing,Ink Smudge,145,66789,1635,292721.82
29,Finishing,Finishing Defect,154,66449,1631,311540.55
47,Sewing,Finishing Defect,142,66953,1622,294386.01
33,Finishing,Print Cracking,137,62717,1619,305542.04
21,Final,Ink Smudge,153,69015,1618,287460.00
11,Fabric,Finishing Defect,144,68251,1605,284648.80
25,Final,Size Variance,159,64771,1596,289917.28
46,Sewing,Fabric Defect,139,59702,1570,277636.46
9,Fabric,Color Misalignment,149,63600,1549,291470.91
38,Printing,Finishing Defect,136,58535,1531,279863.68
37,Printing,Fabric Defect,155,66628,1523,282639.90
5,Cutting,Packing Error,142,62480,1516,264724.61
14,Fabric,Packing Error,134,59378,1511,269075.13
6,Cutting,Print Cracking,155,67953,1511,289695.98
20,Final,Finishing Defect,131,59062,1500,274329.39
36,Printing,Color Misalignment,133,56686,1467,266302.70
23,Final,Packing Error,141,59483,1439,264061.86
45,Sewing,Color Misalignment,131,58081,1408,250957.04
42,Printing,Print Cracking,124,55708,1401,260103.57
28,Finishing,Fabric Defect,121,53728,1381,250256.53
51,Sewing,Print Cracking,124,57539,1374,253959.46
12,Fabric,Ink Smudge,129,55606,1341,236584.74
48,Sewing,Ink Smudge,126,59034,1335,246317.05

In [51]:
print(dfs['Quality'].columns.tolist())

['QC_ID', 'Inspection_Date', 'Product_ID', 'Product_Name', 'Stage', 'Inspected_Qty', 'Passed_Qty', 'Rejected_Qty', 'Defect_Type', 'Root_Cause', 'Estimated_Loss_EGP', 'Data_Class']

In [55]:
# Purchase Orders and Supplier Performance Analysis (Corrected Column Names)
po_df = dfs['Purchase_Orders']

# Calculate Total Cost per row
po_df['Total_Cost_EGP'] = po_df['Ordered_Qty'] * po_df['Unit_Cost_EGP']

supplier_summary = po_df.groupby('Supplier_ID').agg(
    Total_POs=('PO_ID', 'count'),
    Total_Ordered_Qty=('Ordered_Qty', 'sum'),
    Total_Accepted_Qty=('Accepted_Qty', 'sum'),
    Total_Rejected_Qty=('Rejected_Qty', 'sum'),
    Total_Spend=('Total_Cost_EGP', 'sum')
).reset_index().sort_values(by='Total_Spend', ascending=False)

print("--- Purchase Orders & Supplier Summary ---")
display(supplier_summary)

--- Purchase Orders & Supplier Summary ---

,Supplier_ID,Total_POs,Total_Ordered_Qty,Total_Accepted_Qty,Total_Rejected_Qty,Total_Spend
6,SUP07,335,1670310,1641863,28447,84758330.19
2,SUP03,291,1512995,1487359,25636,82890481.05
7,SUP08,316,1561535,1534800,26735,81631567.57
9,SUP10,300,1548633,1522861,25772,78086771.32
10,SUP11,305,1588731,1558083,30648,76543735.69
8,SUP09,289,1418669,1391325,27344,76331660.19
4,SUP05,297,1468322,1441678,26644,73873102.51
5,SUP06,312,1612618,1584414,28204,72353891.25
1,SUP02,297,1480913,1456129,24784,69784488.30
3,SUP04,281,1390120,1367154,22966,65328364.39
11,SUP12,298,1455268,1428373,26895,61850511.20
0,SUP01,279,1319672,1297865,21807,61340301.15

In [54]:
print(dfs['Purchase_Orders'].columns.tolist())

['PO_ID', 'Order_Date', 'Supplier_ID', 'Material_ID', 'Material_Name', 'Unit', 'Ordered_Qty', 'Unit_Cost_EGP', 'Promised_Date', 'Actual_Receipt_Date', 'Accepted_Qty', 'Rejected_Qty', 'Data_Class']

In [59]:
# Daily Web Traffic and Conversion Analysis (Corrected)
web_df = dfs['Web_Traffic_Daily']

web_summary = pd.DataFrame({
    'Metric': ['Total Sessions', 'Total Users', 'Total Orders', 'Avg Conversion Rate', 'Avg Add To Cart Rate', 'Avg Page Load Sec'],
    'Value': [
        web_df['Sessions'].sum(),
        web_df['Users'].sum(),
        web_df['Orders'].sum(),
        web_df['Conversion_Rate'].mean(),
        web_df['Add_To_Cart_Rate'].mean(),
        web_df['Avg_Page_Load_Sec'].mean()
    ]
})

print("--- Web Traffic Daily Overall Performance Summary ---")
display(web_summary)

--- Web Traffic Daily Overall Performance Summary ---

                 Metric         Value
0        Total Sessions  1.678059e+06
1           Total Users  1.375482e+06
2          Total Orders  4.746200e+04
3   Avg Conversion Rate  2.860210e-02
4  Avg Add To Cart Rate  1.020432e-01
5     Avg Page Load Sec  2.624407e+00

In [57]:
dfs["Web_Traffic_Daily"].columns

Index(['Date', 'Sessions', 'Users', 'New_User_Pct', 'Mobile_Pct',
       'Add_To_Cart_Rate', 'Checkout_Rate', 'Orders', 'Conversion_Rate',
       'Avg_Page_Load_Sec', 'Data_Class'],
      dtype='object')

In [62]:
downtime_df = dfs['Machine_Downtime']
downtime_summary = downtime_df.groupby(['Machine_ID', 'Reason']).agg(
    Total_Incidents=('Downtime_ID', 'count'),
    Total_Downtime_Hours=('Downtime_Hours', 'sum')
).reset_index().sort_values(by='Total_Downtime_Hours', ascending=False)

print("--- Machine Downtime Analysis ---")
display(downtime_summary)

--- Machine Downtime Analysis ---

   Machine_ID              Reason  Total_Incidents  Total_Downtime_Hours
32     PR-M02    Mechanical fault               62                 176.5
11     CUT-02  Setup / changeover               49                 172.9
38     PR-M03    Mechanical fault               60                 162.4
62    SEW-L02    Mechanical fault               58                 138.8
44     PR-M04    Mechanical fault               58                 138.2
..        ...                 ...              ...                   ...
33     PR-M02   Operator shortage               20                  35.7
21    PACK-01   Operator shortage               26                  35.5
3      CUT-01   Operator shortage               21                  35.3
45     PR-M04   Operator shortage               23                  33.5
48     PR-M05    Electrical fault               21                  32.7

[72 rows x 4 columns]

In [61]:
dfs["Machine_Downtime"].columns

Index(['Downtime_ID', 'Date', 'Machine_ID', 'Business_Area', 'Downtime_Hours',
       'Reason', 'Planned', 'Data_Class'],
      dtype='object')

In [63]:
print_df = dfs['Printing_Batches']
print_summary = print_df.groupby('Print_Type').agg(
    Total_Batches=('Print_Batch_ID', 'count'),
    Planned_Qty=('Planned_Qty', 'sum'),
    Printed_Qty=('Printed_Qty', 'sum'),
    Total_Ink_Cost=('Ink_or_Consumable_Cost_EGP', 'sum'),
    Total_Rework_Cost=('Rework_Cost_EGP', 'sum')
).reset_index()

print("--- Printing Batches Performance ---")
display(print_summary)

--- Printing Batches Performance ---

,Print_Type,Total_Batches,Planned_Qty,Printed_Qty,Total_Ink_Cost,Total_Rework_Cost
0,Digital,492,1552296,1529057,6603660.94,210571.10
1,Heat Transfer,467,1467381,1446027,6600500.48,193867.57
2,Screen,468,1483169,1461024,6451167.53,197667.80
3,Water-Based,473,1448421,1424624,6420258.08,193481.18

In [66]:
# Product Master Analysis by Product Family and Gender (Corrected Column Names)
prod_master = dfs['Product_Master']

product_summary = prod_master.groupby(['Product_Family', 'Gender']).agg(
    Total_SKUs=('SKU', 'count'),
    Avg_Retail_Price=('Public_Retail_Price_EGP', 'mean')
).reset_index().sort_values(by='Total_SKUs', ascending=False)

print("--- Product Master Category Summary ---")
display(product_summary)

--- Product Master Category Summary ---

     Product_Family  Gender  Total_SKUs  Avg_Retail_Price
3  Pajamas/Homewear   Girls          17        307.470588
2  Pajamas/Homewear    Boys          16        308.250000
4  Pajamas/Homewear   Women           9        388.000000
7          T-Shirts    Boys           6        330.000000
1         Kids Sets  Unisex           4        400.000000
5       Sweatshirts    Boys           3        549.000000
6       Sweatshirts   Girls           3        549.000000
0         Kids Sets   Girls           1        400.000000

In [65]:
dfs["Product_Master"].columns

Index(['Product_ID', 'SKU', 'Product_Name', 'Brand', 'Product_Family',
       'Gender', 'Audience', 'Catalog_Season', 'Sizes',
       'Public_Retail_Price_EGP', 'Public_Catalog_Source',
       'Verification_Class'],
      dtype='object')

In [72]:
# Suppliers Analysis by Primary Category and Contract Status (Corrected Column Names)
supp_df = dfs['Suppliers']

supp_summary = supp_df.groupby(['Primary_Category', 'Contracted']).agg(
    Total_Suppliers=('Supplier_ID', 'count'),
    Avg_Payment_Terms=('Payment_Terms_Days', 'mean')
).reset_index().sort_values(by='Total_Suppliers', ascending=False)

print("--- Suppliers Summary ---")
display(supp_summary)

--- Suppliers Summary ---

       Primary_Category Contracted  Total_Suppliers  Avg_Payment_Terms
6                 Trims        Yes                3               25.0
3             Packaging        Yes                2               37.5
0                Fabric         No                2               45.0
5                 Trims         No                2               37.5
1                Fabric        Yes                1               15.0
2             Packaging         No                1               45.0
4  Printing Consumables        Yes                1               60.0

In [70]:
dfs["Suppliers"].columns

Index(['Supplier_ID', 'Supplier_Name', 'Primary_Category', 'Governorate',
       'Payment_Terms_Days', 'Contracted', 'Data_Class'],
      dtype='object')

In [75]:
# Materials Analysis by Category and Lead Time (Corrected Column Names)
materials_df = dfs['Materials']

materials_summary = materials_df.groupby('Material_Category').agg(
    Total_Materials=('Material_ID', 'count'),
    Avg_Lead_Time_Days=('Standard_Lead_Time_Days', 'mean')
).reset_index().sort_values(by='Total_Materials', ascending=False)

print("--- Materials Summary ---")
display(materials_summary)

--- Materials Summary ---

  Material_Category  Total_Materials  Avg_Lead_Time_Days
0            Fabric                4                11.0
3             Trims                4                10.5
1         Packaging                2                 8.5
2          Printing                2                14.0

In [74]:
dfs["Materials"].columns

Index(['Material_ID', 'Material_Name', 'Unit', 'Material_Category',
       'Standard_Lead_Time_Days', 'Data_Class'],
      dtype='object')

In [76]:
locations_df = dfs['Locations']
locations_summary = locations_df.groupby('Location_Type').agg(
    Total_Locations=('Location_ID', 'count')
).reset_index()

print("--- Business Locations Breakdown ---")
display(locations_summary)

bu_df = dfs['Business_Units']
print("--- Business Units Overview ---")
display(bu_df)

--- Business Locations Breakdown ---

          Location_Type  Total_Locations
0       B2B / Wholesale                1
1         Digital Store                1
2  Factory / Production                1
3           Head Office                1
4          Retail Store                1

--- Business Units Overview ---

,Business_Unit,Function,Public_Capacity,Source_URL,Verification_Class
0,LEO DESIGN,"Fashion design, pattern making, 3D visualization",Not publicly stated,https://www.el-sharnouby.com/,Public company fact
1,LEO TEX,Woven fabric manufacturing,Integrated textile manufacturing; exact capaci...,https://www.el-sharnouby.com/services,Public company fact
2,LEO PRODUCTION HUB,Garment manufacturing,"Up to 5,000 pieces/day",https://www.el-sharnouby.com/services,Public company fact
3,LEO PRINT,Textile and garment printing,"Up to 20,000 garments/day and 6,000 fabric met...",https://www.el-sharnouby.com/services,Public company fact
4,LEO MODA,"Retail, online and wholesale apparel brand",Delivery across Egypt; retail + wholesale chan...,https://leo.moda/,Public company fact

In [77]:
ops_df = dfs['Group_Operations']
print("--- Group Operations Overview ---")
display(ops_df.head())

--- Group Operations Overview ---

,Month,Business_Unit,Primary_KPI,Volume,Operational_Efficiency_Pct,Open_Issues_Count,Data_Class
0,2023-10-01,LEO DESIGN,Designs_Completed,48,85.1,2,Modeled monthly operational summary using publ...
1,2023-10-01,LEO TEX,Fabric_Meters,129278,91.5,6,Modeled monthly operational summary using publ...
2,2023-10-01,LEO PRODUCTION HUB,Garments_Produced,78490,88.5,9,Modeled monthly operational summary using publ...
3,2023-10-01,LEO PRINT,Print_Units,70454,86.7,1,Modeled monthly operational summary using publ...
4,2023-10-01,LEO MODA,Sales_Units,36484,87.6,1,Modeled monthly operational summary using publ...

In [78]:
dict_df = dfs['Data_Dictionary']
print("--- Data Dictionary Overview ---")
display(dict_df.head())

--- Data Dictionary Overview ---

,Table,Grain,Purpose,Real_vs_Modeled
0,Product_Master.csv,1 row per public product,Public product catalog master and public retai...,Public/verified master data
1,Business_Units.csv,1 row per company business unit,Group structure and public capacity facts,Public/verified facts
2,Locations.csv,1 row per channel / operating location,"Retail, online, wholesale, HQ and factory context",Public facts where available; exact factory ad...
3,Customers.csv,1 row per anonymized customer ID,Customer segmentation / retention / RFM,Modeled/anonymized training data
4,Sales_Transactions.csv,1 row per invoice line,"Sales, margin, returns, channel and product an...",Modeled transactions anchored to public produc...

In [79]:
briefs_df = dfs['Case_Briefs']
print("--- Case Briefs / Roadmap Overview ---")
display(briefs_df.head(10))

--- Case Briefs / Roadmap Overview ---

,Card_No,Title,Business_Problem,Expected_Deliverable
0,1,Executive Sales & Profitability,"Revenue is growing, but management is unsure w...","Build an executive view of revenue, units, gro..."
1,2,Customer 360 & Retention,"The business has a growing customer base, but ...","Create customer segments using RFM/cohorts, re..."
2,3,Branch & Channel Performance,"Retail, online and wholesale operate different...","Compare channel growth, margin, returns, baske..."
3,4,Inventory & Demand Planning,Some SKUs tie up cash while other fast movers ...,"Perform ABC/XYZ analysis, stock turns, days of..."
4,5,Marketing Effectiveness,"Spend is distributed across platforms, but man...","Measure ROAS, CAC, CTR, conversion, attributed..."
5,6,Factory Production & Bottlenecks,Production orders show uneven efficiency and d...,"Analyze throughput, plan vs actual, reject rat..."
6,7,"Quality, Returns & Cost of Poor Quality",Customer returns and QC defects are not always...,"Build defect Pareto, quality loss, product/sta..."
7,8,Printing Performance & Downtime,Printing yield and rework vary by machine and ...,"Analyze machine yield, defect rate, reprint co..."
8,9,Supply Chain & Materials,Material availability and supplier reliability...,"Measure supplier lead time, on-time delivery, ..."
9,10,Integrated Management Story + Forecast,Leadership needs one connected story from mark...,Deliver a management dashboard/story that link...

In [97]:
dfs['Case_Briefs'].Business_Problem

0    Revenue is growing, but management is unsure w...
1    The business has a growing customer base, but ...
2    Retail, online and wholesale operate different...
3    Some SKUs tie up cash while other fast movers ...
4    Spend is distributed across platforms, but man...
5    Production orders show uneven efficiency and d...
6    Customer returns and QC defects are not always...
7    Printing yield and rework vary by machine and ...
8    Material availability and supplier reliability...
9    Leadership needs one connected story from mark...
Name: Business_Problem, dtype: object

In [82]:
# Product BOM Structure Analysis (Corrected Column Names)
bom_df = dfs['Product_BOM']

bom_summary = bom_df.groupby(['Product_ID', 'Product_Name']).agg(
    Total_Materials_Count=('Material_ID', 'count'),
    Total_Required_Per_Unit=('Required_Per_Unit', 'sum')
).reset_index().sort_values(by='Total_Materials_Count', ascending=False)

print("--- Product BOM Structure Summary ---")
display(bom_summary)

--- Product BOM Structure Summary ---

,Product_ID,Product_Name,Total_Materials_Count,Total_Required_Per_Unit
1,P002,Summer children's girls-turtle,6,3.774
2,P003,Summer children's girls-Hello kitty Rose & tur...,6,3.945
3,P004,Summer children's girls-Hello kitty black&white,6,4.003
7,P008,Summer children's boys-SpongeBob,6,3.572
4,P005,Summer children's boys-Black and orange,6,3.784
5,P006,Summer children's boys-Sonic,6,3.724
6,P007,Summer children's boys-Black and turquoise,6,3.856
9,P010,Boys' summer t-shirt-olive,6,3.516
8,P009,Boys' summer t-shirt-Aubergine,6,3.544
10,P011,Boys' summer t-shirt-Navy blue,6,4.132
11,P012,Boys' summer t-shirt-light beige,6,3.919
25,P026,Boys' summer pajamas-Bluey,6,3.604
12,P013,Boys' summer t-shirt-Beige,6,4.038
13,P014,Boys' summer t-shirt-Black,6,3.866
14,P015,Girls' summer pajamas-Stay cool,6,3.792
16,P017,Girls' summer pajamas-flower,6,3.726
17,P018,Boys' summer pajamas-Wear your attitude,6,3.542
18,P019,Boys' summer pajamas- Seeds OF,6,3.954
19,P020,Boys' summer pajamas-Rock Band,6,3.730
26,P027,Girls' pajamas - I'm Just a girl,6,3.725
20,P021,Girls' summer pajamas-Minnie Mouse,6,3.867
22,P023,Girls' summer pajamas-Dumbo,6,3.789
23,P024,Boys' summer pajamas-Mickey,6,3.833
24,P025,Boys' summer pajamas-Snoopy,6,3.543
42,P043,Girls' autumn pajamas-Snow White,6,3.772
41,P042,Girls' autumn pajamas-Cheeky Charmins,6,3.933
30,P031,Boys' pajamas -Don't Even!,6,4.056
58,P059,Positive vibes - 2024بيجامة حريمي صيفي,6,4.213
54,P055,Scooby-Doo - بيجامة حريمي صيفي2024,6,4.149
49,P050,Yellow - طقم تيشيرت وشورت اطفال صيفي,6,3.737
38,P039,Boys' Autumn Pajamas-Spider Man,6,3.842
39,P040,Boys' Autumn Pajamas-Loony Tunes,6,3.640
53,P054,Gazelle - بيجامة حريمي صيفي2024,6,3.520
56,P057,Save the planet بيجامة حريمي صيفي - 2024,6,4.038
55,P056,BATGIRL - بيجامة حريمي صيفي2024,6,3.500
51,P052,Teddy bear - بيجامة حريمي صيفي2024,6,3.981
52,P053,PINK panther - بيجامة حريمي صيفي2024,6,3.599
45,P046,Mustard - طقم تيشيرت وشورت اطفال صيفي,6,3.573
50,P051,Ice cream - بيجامة حريمي صيفي2024,6,4.058
48,P049,Fuchsia - طقم تيشيرت وشورت اطفال صيفي,6,4.170
46,P047,Mauve - طقم تيشيرت وشورت اطفال صيفي,6,3.608
43,P044,Girls' autumn pajamas-Ice Cream,6,3.786
0,P001,Summer children's girls-Happy,5,4.072
21,P022,Girls' summer pajamas-Stitch,5,3.470
15,P016,Girls' summer pajamas-Watercolor Floral,5,3.678
36,P037,Girls' sweatshirt-Flower,5,3.983
35,P036,Girls' sweatshirt-Tinker Bell,5,3.541
40,P041,Boys' Autumn Pajamas-Jurassic Park,5,3.945
32,P033,Boys' sweatshirt-LEO,5,4.059
33,P034,Boys' sweatshirt-black and white,5,3.922
34,P035,Girls' sweatshirt-Fuchsia,5,3.526
29,P030,Boys' pajamas -Mickey Mouse,5,4.128
28,P029,Girls' pajamas-Daylife+kuromi,5,3.958
27,P028,Girls' summer pajamas,5,4.129
37,P038,Boys' Autumn Pajamas-Mickey Mouse,5,4.075
31,P032,Boys' sweatshirt-blue,5,4.122
44,P045,Girls' autumn pajamas-Stitch,5,4.011
47,P048,Semon - طقم تيشيرت وشورت اطفال صيفي,5,4.052
57,P058,OHANA - بيجامة حريمي صيفي 2024,5,4.135

In [81]:
dfs["Product_BOM"].columns

Index(['Product_ID', 'Product_Name', 'Material_ID', 'Material_Name',
       'Required_Per_Unit', 'Unit', 'Data_Class'],
      dtype='object')

In [86]:
# Inventory Snapshot and Movement Analysis (Corrected Column Names)
inv_history_df = dfs['Inventory_History']

inv_summary = inv_history_df.groupby(['Location_Name', 'Product_Name']).agg(
    Total_Opening_Stock=('Opening_Stock', 'sum'),
    Total_Received=('Received_Qty', 'sum'),
    Total_Sold=('Sold_Qty', 'sum'),
    Total_Returned=('Returned_Qty', 'sum'),
    Total_Damaged=('Damaged_Qty', 'sum'),
    Total_Closing_Stock=('Closing_Stock', 'sum'),
    Avg_Days_Of_Cover=('Days_of_Cover', 'mean'),
    Total_Stockout_Days=('Stockout_Days_In_Month', 'sum')
).reset_index().sort_values(by='Total_Sold', ascending=False)

print("--- Inventory Movement and Stockout Analysis ---")
display(inv_summary)

--- Inventory Movement and Stockout Analysis ---

,Location_Name,Product_Name,Total_Opening_Stock,Total_Received,Total_Sold,Total_Returned,Total_Damaged,Total_Closing_Stock,Avg_Days_Of_Cover,Total_Stockout_Days
40,El-Sharnouby Wholesale Desk,Ice cream - بيجامة حريمي صيفي2024,25930,62489,63456,1158,229,25892,13.911111,0
53,El-Sharnouby Wholesale Desk,Summer children's girls-Happy,9968,54358,60438,1476,219,10106,7.938889,67
52,El-Sharnouby Wholesale Desk,Summer children's boys-SpongeBob,28286,55685,57048,1092,201,27915,21.058333,17
37,El-Sharnouby Wholesale Desk,Girls' sweatshirt-Flower,44716,53834,53076,828,193,46109,64.111111,0
29,El-Sharnouby Wholesale Desk,Girls' pajamas-Daylife+kuromi,25147,41144,41724,858,152,25273,21.025000,0
...,...,...,...,...,...,...,...,...,...,...
93,LEO MODA - Sidi Bishr Store,Girls' summer pajamas-Stitch,8576,505,544,14,8,8543,619.533333,0
175,LEO MODA Online Store,Teddy bear - بيجامة حريمي صيفي2024,9086,504,529,43,7,9097,725.944444,0
149,LEO MODA Online Store,Girls' summer pajamas-Dumbo,63494,3769,455,41,5,66844,5530.527778,0
116,LEO MODA - Sidi Bishr Store,Teddy bear - بيجامة حريمي صيفي2024,5019,403,432,21,10,5001,549.122222,0
90,LEO MODA - Sidi Bishr Store,Girls' summer pajamas-Dumbo,55409,3307,394,11,5,58328,5589.491667,0

In [84]:
dfs['Inventory_History'].columns

Index(['Snapshot_Month', 'Location_ID', 'Location_Name', 'Product_ID', 'SKU',
       'Product_Name', 'Opening_Stock', 'Received_Qty', 'Sold_Qty',
       'Returned_Qty', 'Damaged_Qty', 'Closing_Stock', 'Avg_Daily_Sales_90D',
       'Safety_Stock_Units', 'Reorder_Point_Units', 'Supplier_Lead_Time_Days',
       'Days_of_Cover', 'Stockout_Days_In_Month', 'Data_Class'],
      dtype='object')